#!/bin/bash
#PBS -N gatk_annotation_job
#PBS -l nodes=1:ppn=4
#PBS -l walltime=12:00:00
#PBS -l mem=16gb
#PBS -o output_gatk_annotation.log
#PBS -e error_gatk_annotation.log
#PBS -V

# Corrigir o caminho do Conda
source /home/jrodolfo/projects/miniconda3/etc/profile.d/conda.sh  # Verifique se este é o caminho correto

# Ativar o ambiente Conda onde o gatk está instalado
conda activate gatk

# Corrigir o caminho do diretório de trabalho
cd /home/jrodolfo/projects/genomes/human_variant_call

chmod +x anotation_process.sh

bash anotation_process.sh
